'use strict';
const byId=id=>document.getElementById(id);
const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TKEY='ai-analyst-thoughts-v1';let atlas,profileId,cardId,step=0,attempts={},answerKeys;
try{const p=JSON.parse(localStorage.getItem(TKEY)||'{}');if(p&&typeof p==='object'&&!Array.isArray(p))attempts=p}catch{}
const steps=['识别假设并建模','加入约束、反驳与修正','陌生领域迁移'];
const selected=()=>atlas.cards.find(c=>c.id===cardId);
function attempt(){return attempts[cardId]??={answers:['','',''],step:0,model_seen:false}}
function persist(){try{localStorage.setItem(TKEY,JSON.stringify(attempts));return true}catch{byId('thought-status').textContent='存储不可用，请导出练习。';return false}}
function saveThought(){const p=attempt();p.answers[step]=byId('thought-answer').value;p.step=step;p.updated_at=new Date().toISOString();return persist()}
function links(ids){return ids.map(id=>{const s=atlas.sources.find(x=>x.id===id);return `<a target="_blank" rel="noopener" href="${safe(s.url)}">${safe(s.id)} · ${safe(s.title)}</a>`}).join(' · ')}
function visibleProfiles(side){const q=(byId('profile-search')?.value||'').trim().toLowerCase();return atlas.profiles.filter(x=>x.side===side&&JSON.stringify([x.name,x.role,x.scope,x.focus]).toLowerCase().includes(q))}
function showProfile(){const p=atlas.profiles.find(x=>x.id===profileId);byId('profile-buttons').innerHTML=['buy','sell'].map(side=>`<div class="profile-group"><p class="eyebrow">${side==='buy'?'BUY SIDE / 买方与创投':'SELL SIDE / 卖方'} · ${atlas.profiles.filter(x=>x.side===side).length}</p>${visibleProfiles(side).map(x=>`<button data-profile="${safe(x.id)}" aria-pressed="${x.id===profileId}">${safe(x.name)}</button>`).join('')}</div>`).join('');byId('profile-buttons').querySelectorAll('button').forEach(b=>b.onclick=()=>{profileId=b.dataset.profile;showProfile()});byId('profile').innerHTML=`<h3>${safe(p.name)}</h3><p>${safe(p.role)}</p><p><strong>关注与推理路径：</strong>${safe(p.scope)}</p><p>${p.focus.map(safe).join(' / ')}</p><p class="muted">${safe(p.boundary)}</p><p><strong>未解决：</strong>${p.gaps.map(safe).join('；')}</p>`;
if(p.current_role)byId('profile').innerHTML+=`<p class="muted"><strong>当前身份核查：</strong>${safe(typeof p.current_role==='string'?p.current_role:[p.current_role.title,p.current_role.as_of,p.current_role.access].filter(Boolean).join(' · '))}</p>`;
if(p.assessment)byId('profile').innerHTML+=`<p><strong>材料评估：</strong>${safe(p.assessment.strength)}</p><p class="muted"><strong>薄弱处：</strong>${safe(p.assessment.weakness)}</p>`;
byId('thought-cards').innerHTML=atlas.cards.filter(c=>c.profile===profileId).map(c=>`<article class="thought-card"><span class="tag">${safe(c.id)} · ${c.tags.map(safe).join(' / ')}</span><h3>${safe(c.title)}</h3><p><strong>材料观点：</strong>${safe(c.source_paraphrase)}</p><details><summary>查看编辑模型、边界与检验</summary><dl><dt>我们的模型</dt><dd>${safe(c.model)}</dd><dt>适用边界</dt><dd>${safe(c.boundary)}</dd><dt>最强反例</dt><dd>${safe(c.counterexample)}</dd><dt>证伪所需证据</dt><dd>${safe(c.test)}</dd></dl><p class="muted">${safe(c.attribution)}</p></details><p class="status">${links(c.source_ids)}<br>${safe(c.locator)} · ${safe(c.forecast_outcome)}</p><button data-card="${safe(c.id)}">用这项方法挑战我 →</button></article>`).join('');byId('thought-cards').querySelectorAll('button').forEach(b=>b.onclick=()=>{saveThought();cardId=b.dataset.card;byId('thought-select').value=cardId;step=attempt().step||0;drawChallenge();byId('challenge').scrollIntoView({behavior:'smooth'})});byId('timeline').innerHTML=p.timeline.map(t=>`<p><strong>${safe(t.date==='undated'?'日期未知（流程页）':t.date)}</strong> · ${safe(t.text)}<br>${links(t.source_ids)}</p>`).join('');byId('comparison').textContent=p.comparison+' '+atlas.comparison;}
function drawChallenge(){const c=selected(),p=attempt();byId('thought-stage').textContent=`合成训练 · ${step+1}/3 · ${steps[step]}`;byId('thought-title').textContent=c.title;byId('thought-question').textContent=[c.question,c.constraint,c.transfer][step];byId('thought-answer').value=p.answers[step]||'';byId('thought-next').disabled=step===2;byId('thought-key').hidden=true;byId('thought-key').textContent='';byId('thought-status').textContent='未进行AI评分。';}
function reviewPrompt(){const c=selected(),p=attempt();return `使用 $ai-infrastructure-analyst 评审以下合成练习。区分材料转述与编辑归纳，不模仿人物，不臆测投资决策。只评审实际答案，未测试项标未评估；先指出一个有效步骤和一个具体缺口，然后只问一个下一问题；没有明确请求不要泄露后续答案。\n方法：${c.id} ${c.title}\n归属：${c.attribution}\n来源：${c.source_ids.map(id=>atlas.sources.find(x=>x.id===id).url).join('\n')}\n定位：${c.locator}\n已呈现的场景与问题：${[c.question,c.constraint,c.transfer].slice(0,step+1).join("\n")}\n当前题目：${[c.question,c.constraint,c.transfer][step]}\n答题记录：${JSON.stringify(p.answers)}\n参考模型已主动查看：${p.model_seen}\n技能：${c.tags.join('/')}`}
async function initThoughts(){try{const res=await fetch('thought-atlas.json?v=20261006-early');if(!res.ok)throw Error('source unavailable');atlas=await res.json();profileId=atlas.profiles[0].id;cardId=atlas.cards[0].id;step=attempt().step||0;byId('atlas-count').textContent=`${atlas.profiles.length}个人物/机构档案（${atlas.profiles.filter(p=>p.side==='buy').length}买方/创投 + ${atlas.profiles.filter(p=>p.side==='sell').length}卖方） · ${atlas.sources.length}份方法材料 · ${atlas.cards.length}张挑战卡 · ${atlas.as_of}`;byId('thought-select').innerHTML=atlas.cards.map(c=>`<option value="${safe(c.id)}">${safe(c.id)} · ${safe(c.title)}</option>`).join('');byId('thought-select').value=cardId;byId('thought-select').onchange=()=>{saveThought();cardId=byId('thought-select').value;step=attempt().step||0;drawChallenge()};byId('thought-save').onclick=()=>{if(saveThought())byId('thought-status').textContent='已保存在本浏览器；未进行AI评分。'};byId('thought-next').onclick=()=>{if(!byId('thought-answer').value.trim()){byId('thought-status').textContent='先尝试当前问题再进入下一阶段。';return}saveThought();step=Math.min(2,step+1);attempt().step=step;persist();drawChallenge()};byId('thought-model').onclick=async()=>{try{if(!answerKeys){const r=await fetch('thought-answer-keys.json?v=20261006-early');if(!r.ok)throw Error('answer unavailable');answerKeys=await r.json()}const key=answerKeys[selected().id];if(!key)throw Error('answer unavailable');attempt().model_seen=true;persist();byId('thought-key').textContent='编辑参考（非人物原话）：'+key;byId('thought-key').hidden=false}catch{byId('thought-status').textContent='参考模型读取失败，请稍后重试。'}};byId('thought-copy').onclick=async()=>{saveThought();try{await navigator.clipboard.writeText(reviewPrompt());byId('thought-status').textContent='已复制；在ChatGPT中评审，不是网页在线评分。'}catch{byId('thought-status').textContent='复制不可用，请导出练习记录。'}};byId('thought-export').onclick=()=>{saveThought();const blob=new Blob([JSON.stringify({as_of:atlas.as_of,evaluator:'not assessed',attempts,prompt:reviewPrompt()},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='analyst-thought-practice.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};byId('source-list').innerHTML=atlas.sources.map(s=>`<li>${links([s.id])}<p>${safe(s.date||'无发布日期')} · ${safe(s.authors)}</p><p>${safe(s.summary)}</p><p class="muted">访问边界：${safe(s.access)}</p></li>`).join('');byId('profile-search').oninput=showProfile;showProfile();drawChallenge()}catch(err){byId('atlas-count').textContent='思想材料读取失败。请刷新，或下载thought-atlas.json查看。';console.error(err)}}
initThoughts();

